import React from 'react';
import { BUILD, CASE, CHAPTERS, INVARIANTS } from '../data/land2buildData';
import { GithubIcon } from '../components/Icons';
import {
  CaseStudyBar,
  CaseStudyCta,
  CaseStudyFooter,
  Chapter,
  Figures,
} from '../components/CaseStudyParts';

export const Land2Build: React.FC = () => (
  <>
    <CaseStudyBar />

    <main>
      {/* ---------- hero ---------- */}
      <section className="section cs-hero">
        <div className="shell">
          <p className="sec-index rise" data-in="true">
            <b>{CASE.kicker}</b>
          </p>
          <h1 className="cs-title rise" data-in="true">
            {CASE.title}
          </h1>
          <p className="cs-lede rise" data-in="true">
            {CASE.summary}
          </p>

          <dl className="cs-meta rise" data-in="true">
            {CASE.meta.map((m) => (
              <div key={m.k}>
                <dt>{m.k}</dt>
                <dd>{m.v}</dd>
              </div>
            ))}
          </dl>

          <p className="stack-line rise" data-in="true">
            {CASE.stack.map((s, i) => (
              <React.Fragment key={s}>
                {i > 0 && <i>/</i>}
                {s}
              </React.Fragment>
            ))}
          </p>

          <div className="hero-actions rise" data-in="true" style={{ marginTop: '2rem' }}>
            <a className="btn btn-lg" href={CASE.repo} target="_blank" rel="noopener noreferrer">
              <GithubIcon size={15} /> Read the source
            </a>
          </div>
        </div>
      </section>

      <section className="shell" aria-label="Build">
        <Figures rows={BUILD} />
      </section>

      {/* ---------- 01 context ---------- */}
      <Chapter c={CHAPTERS[0]}>
        <div className="prose rise">
          <p>
            Someone planning a house on a plot in India wants three things early and cheaply: what
            can I fit here, roughly what will it cost, and when can we pour concrete without the
            monsoon undoing it.
          </p>
          <p>
            Each of those is normally a separate professional and a separate week. Land2Build
            takes a plot — located on a map, with a size and a foundation type — and a sentence
            describing the building, and answers all three in the browser: a walkable 3D model, a
            bill of materials in rupees, and a weather view for the build season.
          </p>
          <p>
            There is no server anywhere in that. Projects live in IndexedDB, the 3D runs on the
            GPU through Three.js, and the only things it reaches out to are a geocoder, a weather
            API and a language model.
          </p>
        </div>
      </Chapter>

      {/* ---------- 02 the line ---------- */}
      <Chapter c={CHAPTERS[1]}>
        <div className="prose rise">
          <p>
            The obvious way to build &ldquo;AI architecture&rdquo; in 2026 is to send the brief to
            an image model and return a render. It demos extremely well. It is also useless for
            the actual question, because a picture of a house has no dimensions you can measure,
            no rooms you can count, and no guarantee that the bedroom it drew fits on the plot.
          </p>
          <p>
            So the model here has one narrow job: read a sentence like{' '}
            <em>&ldquo;modern two-storey house with a flat roof&rdquo;</em> and return a{' '}
            <strong>typed configuration</strong> — width, length, floors, roof type, wall material,
            design style. That is a parsing problem, which is what language models are genuinely
            good at.
          </p>
          <p>
            Everything downstream of that config is ordinary deterministic code. The model never
            sees the geometry, never places a room and never decides a dimension. It converts
            English into a struct, and then it is done.
          </p>
        </div>
      </Chapter>

      {/* ---------- 03 generation ---------- */}
      <Chapter c={CHAPTERS[2]}>
        <div className="prose rise">
          <p>
            Floor plans are generated by <strong>binary space partitioning</strong> — the same idea
            roguelikes use to lay out dungeons, pointed at a house. Start with the building
            footprint as one rectangle, then recursively split it.
          </p>
          <p>
            Left unconstrained that produces nonsense: corridors two metres long and forty
            centimetres wide. Three rules keep it habitable. A rectangle more than 1.25× wider
            than it is tall must split vertically, and vice versa, so proportions stay sane. The
            split point is random but confined to the middle fifth, so no child is a sliver. And
            recursion stops when another cut would breach the minimum room size.
          </p>
          <p>
            The result is a set of rooms, each tagged with a purpose — living, kitchen, bedroom,
            bathroom, dining, hallway, utility — and with which of its four sides face outward.
            That last flag is what later decides where windows can go and where the front door
            belongs.
          </p>
          <p>
            Seven house types drive different partitioning: a courtyard plan reserves its centre,
            an L-shape carves a corner, a duplex splits into two independent units.
          </p>
        </div>
      </Chapter>

      {/* ---------- 04 three dimensions ---------- */}
      <Chapter c={CHAPTERS[3]}>
        <div className="prose rise">
          <p>
            Extruding a plan into 3D is not just raising rectangles. Each wall needs to know
            whether it is an exterior or interior wall, whether it carries a window, and whether
            it holds the front door — which is exactly the information the generator attached to
            each room.
          </p>
          <p>
            So walls are built from that metadata rather than modelled by hand: an exterior wall
            with a window gets a glazed opening, the room flagged with the entrance gets a framed
            door, and interior walls stay solid. Dimension lines and room labels are drawn from
            the same numbers, so the annotation cannot drift from the geometry — they are the same
            source.
          </p>
        </div>
      </Chapter>

      {/* ---------- 05 proof ---------- */}
      <Chapter c={CHAPTERS[4]}>
        <div className="prose rise">
          <p>
            This is the payoff, and the reason the line in chapter two is drawn where it is.
            Because the plan is data produced by an algorithm, it has properties that can be
            asserted — and a randomised generator is exactly the kind of code that needs them.
          </p>
        </div>

        <ul className="bullets rise" style={{ marginTop: '2rem' }}>
          {INVARIANTS.map((i) => (
            <li key={i.actor}>
              <strong>{i.actor}</strong> — {i.does}
            </li>
          ))}
        </ul>

        <div className="prose rise" style={{ marginTop: '2rem' }}>
          <p>
            Those four properties are checked across twenty-five randomised runs for each of the
            seven house types — <strong>thirty-five test cases</strong> that would catch a
            partitioning bug the moment it appeared, including the intermittent kind that only
            shows up on one random seed in fifty.
          </p>
          <p>
            None of that is available to an image model. You cannot assert that a diffusion output
            has non-overlapping rooms, because it does not have rooms — it has pixels that resemble
            them. Choosing an algorithm over a model cost some visual flair and bought the ability
            to prove the thing is correct.
          </p>
        </div>

        <div style={{ marginTop: '2.5rem' }}>
          <Figures rows={BUILD} />
        </div>
      </Chapter>

      {/* ---------- 06 retrospective ---------- */}
      <Chapter c={CHAPTERS[5]}>
        <div className="prose rise">
          <p>
            <strong>The cost estimate does not follow its own rule.</strong> Having argued that
            the model should not produce numbers, I let it produce the entire bill of materials —
            quantities, unit prices, totals. It returns plausible Indian market figures and I
            cannot verify any of them, which is precisely the failure mode I designed the geometry
            to avoid. It should be a rate table and a quantity takeoff derived from the plan the
            generator already produced; the model should only explain the result.
          </p>
          <p>
            <strong>The plans have no circulation model.</strong> Partitioning guarantees rooms
            do not overlap, not that you can walk between them sensibly. A bedroom can end up
            reachable only through a bathroom, because nothing in the algorithm knows what a
            doorway is for. Adding adjacency rules to the partition step is the obvious next move.
          </p>
          <p>
            <strong>Accounts are a local demo and now say so.</strong> Sign-up writes to IndexedDB
            with no server behind it. Passwords are hashed with PBKDF2 rather than stored, which
            fixes the worst of it, but it is a demo boundary and the README states that plainly
            instead of implying otherwise.
          </p>
        </div>
      </Chapter>

      <CaseStudyCta
        title="The source is open."
        note="Every figure here is checkable against the repository, including the tests. Happy to talk through the partitioning algorithm or where the deterministic line should sit in a tool like this."
      />

      <CaseStudyFooter note="Built in the browser, start to finish" />
    </main>
  </>
);
