/**
 * Case study content for Land2Build.
 *
 * Every figure describes the public repository — house types, tests, files,
 * external services — and is checkable against the source. There are no usage
 * numbers because it is a tool I built, not a product with users.
 */
import type { ChapterMeta } from '../components/CaseStudyParts';

export const CASE = {
  title: 'Land2Build — Generated Floor Plans',
  kicker: 'Case study',
  summary:
    'A construction planner that turns a plot and a sentence into a walkable 3D house. The interesting decision is what the language model is not allowed to do: it reads the brief, but the floor plan is generated by a deterministic algorithm — which means the layout can be tested, and it is.',
  meta: [
    { k: 'Role', v: 'Sole engineer' },
    { k: 'Period', v: '2026' },
    { k: 'Runs on', v: 'The browser — no backend at all' },
    { k: 'Status', v: 'Open source' },
  ],
  stack: [
    'React',
    'TypeScript',
    'Three.js',
    'React Three Fiber',
    'Dexie / IndexedDB',
    'Leaflet',
    'Vitest',
    'Vite',
  ],
  repo: 'https://github.com/Maheshwaran325/Land2Build',
};

export const BUILD = [
  { v: '7', l: 'House types', s: 'standard through courtyard and L-shaped' },
  { v: '35', l: 'Invariant checks', s: 'randomised runs, every house type' },
  { v: '0', l: 'Backend services', s: '3D, storage and maps all in-browser' },
  { v: '3', l: 'External APIs', s: 'Nebius, Open-Meteo, Nominatim' },
];

/** What the generator guarantees about every plan it emits. */
export const INVARIANTS = [
  { actor: 'Inside the footprint', does: 'No room extends past the plot boundary' },
  { actor: 'No overlaps', does: 'Two rooms may share a wall but never occupy the same space' },
  { actor: 'Positive area', does: 'Every room has real width and length, never a degenerate sliver' },
  { actor: 'Unique identity', does: 'Every room carries an id nothing else uses' },
];

export const CHAPTERS: ChapterMeta[] = [
  { index: '01', label: 'Context', title: 'A plot, a sentence, a house.' },
  { index: '02', label: 'The line', title: 'The model does not draw it.' },
  { index: '03', label: 'Generation', title: 'Splitting a rectangle into rooms.' },
  { index: '04', label: 'Three dimensions', title: 'Walls that know what they are.' },
  { index: '05', label: 'Proof', title: 'You can test a plan. You cannot test a picture.' },
  { index: '06', label: 'Retrospective', title: 'The costs are still a guess.' },
];
